const stationList = [];

stationList.push([
    {
        id: 1,
        type: "switch",
        label: "Arm",
        description: "Big toggle switch with cover",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 2,
        type: "button",
        label: "Big Button",
        description: "Large round button",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 3,
        type: "knob",
        label: "Red Knob",
        description: "Red knob",
        currentStatus: null,
        hasBeenPressed: false,
        currentSetting: null,
        previousSetting: null,
    },
    {
        id: 4,
        type: "knob",
        label: "Blue Knob",
        description: "Blue knob",
        currentStatus: null,
        hasBeenPressed: false,
        currentSetting: null,
        previousSetting: null,
    },
    {
        id: 5,
        type: "knob",
        label: "White Knob",
        description: "White knob",
        currentStatus: null,
        hasBeenPressed: false,
        currentSetting: null,
        previousSetting: null,
    },
    {
        id: 6,
        type: "switch",
        label: "Switch 1",
        description: "Far Left Switch",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 7,
        type: "switch",
        label: "Switch 2",
        description: "Second Switch From the Left",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 8,
        type: "switch",
        label: "Switch 3",
        description: "Middle Switch",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 9,
        type: "switch",
        label: "Switch 4",
        description: "Second Switch from the Right",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 10,
        type: "switch",
        label: "Switch 5",
        description: "Far Right Switch",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 11,
        type: "button",
        label: "Button 1",
        description: "Far Left Small Button",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 12,
        type: "button",
        label: "Switch 2",
        description: "Second Small Button From the Left",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 13,
        type: "button",
        label: "Button 3",
        description: "Middle Small Button",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 14,
        type: "button",
        label: "Button 4",
        description: "Second Small Button from the Right",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 15,
        type: "button",
        label: "Button 5",
        description: "Far Right Small Button",
        currentStatus: null,
        hasBeenPressed: false,
    },
]);

stationList.push([
    {
        id: 1,
        type: "switch",
        label: "Arm",
        description: "Big toggle switch with cover",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 2,
        type: "button",
        label: "Big Button",
        description: "Large round button",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 3,
        type: "knob",
        label: "Red Knob",
        description: "Red knob",
        currentStatus: null,
        hasBeenPressed: false,
        currentSetting: null,
        previousSetting: null,
    },
    {
        id: 4,
        type: "knob",
        label: "Blue Knob",
        description: "Blue knob",
        currentStatus: null,
        hasBeenPressed: false,
        currentSetting: null,
        previousSetting: null,
    },
    {
        id: 5,
        type: "knob",
        label: "White Knob",
        description: "White knob",
        currentStatus: null,
        hasBeenPressed: false,
        currentSetting: null,
        previousSetting: null,
    },
    {
        id: 6,
        type: "switch",
        label: "Switch 1",
        description: "Far Left Switch",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 7,
        type: "switch",
        label: "Switch 2",
        description: "Second Switch From the Left",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 8,
        type: "switch",
        label: "Switch 3",
        description: "Middle Switch",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 9,
        type: "switch",
        label: "Switch 4",
        description: "Second Switch from the Right",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 10,
        type: "switch",
        label: "Switch 5",
        description: "Far Right Switch",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 11,
        type: "button",
        label: "Button 1",
        description: "Far Left Small Button",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 12,
        type: "button",
        label: "Switch 2",
        description: "Second Small Button From the Left",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 13,
        type: "button",
        label: "Button 3",
        description: "Middle Small Button",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 14,
        type: "button",
        label: "Button 4",
        description: "Second Small Button from the Right",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 15,
        type: "button",
        label: "Button 5",
        description: "Far Right Small Button",
        currentStatus: null,
        hasBeenPressed: false,
    },
]);

module.exports = stationList;
