const stationList = [];

stationList.push([
    {
        id: 1,
        pin: 33,
        type: "switch",
        subType: "arm",
        label: "Arm",
        description: "Big toggle switch with cover",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 2,
        pin: 32,
        type: "button",
        subType: "big",
        label: "Big Button",
        description: "Large round button",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 3,
        pin: 'A0',
        type: "knob",
        label: "Red Knob",
        description: "Red knob",
        currentStatus: null,
        hasBeenPressed: false,
        currentSetting: null,
        previousSetting: null,
    },
    {
        id: 4,
        pin: 'A2',
        type: "knob",
        label: "Blue Knob",
        description: "Blue knob",
        currentStatus: null,
        hasBeenPressed: false,
        currentSetting: null,
        previousSetting: null,
    },
    {
        id: 5,
        pin: 'A3',
        type: "knob",
        label: "White Knob",
        description: "White knob",
        currentStatus: null,
        hasBeenPressed: false,
        currentSetting: null,
        previousSetting: null,
    },
    {
        id: 6,
        pin: 27,
        type: "switch",
        subType: "small",
        label: "Switch 1",
        description: "Far Left Switch",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 7,
        pin: 28,
        type: "switch",
        subType: "small",
        label: "Switch 2",
        description: "Second Switch From the Left",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 8,
        pin: 29,
        type: "switch",
        subType: "small",
        label: "Switch 3",
        description: "Middle Switch",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 9,
        pin: 30,
        type: "switch",
        subType: "small",
        label: "Switch 4",
        description: "Second Switch from the Right",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 10,
        pin: 31,
        type: "switch",
        subType: "small",
        label: "Switch 5",
        description: "Far Right Switch",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 11,
        pin: 22,
        type: "button",
        subType: "small",
        label: "Button 1",
        description: "Far Left Small Button",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 12,
        pin: 23,
        type: "button",
        subType: "small",
        label: "Switch 2",
        description: "Second Small Button From the Left",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 13,
        pin: 24,
        type: "button",
        subType: "small",
        label: "Button 3",
        description: "Middle Small Button",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 14,
        pin: 25,
        type: "button",
        subType: "small",
        label: "Button 4",
        description: "Second Small Button from the Right",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 15,
        pin: 26,
        type: "button",
        subType: "small",
        label: "Button 5",
        description: "Far Right Small Button",
        currentStatus: null,
        hasBeenPressed: false,
    },
]);

stationList.push([
    {
        id: 1,
        pin: 2,
        type: "switch",
        subType: "arm",
        label: "Arm",
        description: "Big toggle switch with cover",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 2,
        pin: 3,
        type: "button",
        subType: "big",
        label: "Big Button",
        description: "Large round button",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 3,
        pin: 10,
        type: "knob",
        label: "Red Knob",
        description: "Red knob",
        currentStatus: null,
        hasBeenPressed: false,
        currentSetting: null,
        previousSetting: null,
    },
    {
        id: 4,
        pin: 10,
        type: "knob",
        label: "Blue Knob",
        description: "Blue knob",
        currentStatus: null,
        hasBeenPressed: false,
        currentSetting: null,
        previousSetting: null,
    },
    {
        id: 5,
        pin: 10,
        type: "knob",
        label: "White Knob",
        description: "White knob",
        currentStatus: null,
        hasBeenPressed: false,
        currentSetting: null,
        previousSetting: null,
    },
    {
        id: 6,
        pin: 4,
        type: "switch",
        subType: "small",
        label: "Switch 1",
        description: "Far Left Switch",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 7,
        pin: 5,
        type: "switch",
        subType: "small",
        label: "Switch 2",
        description: "Second Switch From the Left",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 8,
        pin: 6,
        type: "switch",
        subType: "small",
        label: "Switch 3",
        description: "Middle Switch",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 9,
        pin: 7,
        type: "switch",
        subType: "small",
        label: "Switch 4",
        description: "Second Switch from the Right",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 10,
        pin: 8,
        type: "switch",
        subType: "small",
        label: "Switch 5",
        description: "Far Right Switch",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 11,
        pin: 9,
        type: "button",
        subType: "small",
        label: "Button 1",
        description: "Far Left Small Button",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 12,
        pin: 10,
        type: "button",
        subType: "small",
        label: "Switch 2",
        description: "Second Small Button From the Left",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 13,
        pin: 11,
        type: "button",
        subType: "small",
        label: "Button 3",
        description: "Middle Small Button",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 14,
        pin: 12,
        type: "button",
        subType: "small",
        label: "Button 4",
        description: "Second Small Button from the Right",
        currentStatus: null,
        hasBeenPressed: false,
    },
    {
        id: 15,
        pin: 52,
        type: "button",
        subType: "small",
        label: "Button 5",
        description: "Far Right Small Button",
        currentStatus: null,
        hasBeenPressed: false,
    },
]);

module.exports = stationList;
